### ISSUE TITLE
Feature suggestion: short method names for default colors

### ISSUE THREAD

**Issue by rinatkhanov** [devxoul/SwiftyColor#4]
I think it'd make sense to make a computed property for each default color. So instead of writing `UIColor.redColor() ~ 0.5` you can write just `UIColor.red ~ 0.5` and get the same object. It's just a few characters shorter, but I believe it makes code more readable.

**Comment by devxoul** [comment]
Nice idea, @rinatkhanov!

It'll be more great if there are more color names such as [CSS colors](http://www.w3schools.com/cssref/css_colornames.asp, but what we need to do first is to make short aliases for color as you mentioned.

It can be done soon. Thanks!

**Comment by devxoul** [comment]
Merged #5.
